# You can update this list if needed
def get_nifty50_symbols():
    return [
        "RELIANCE.NS", "HDFCBANK.NS", "ICICIBANK.NS", "INFY.NS", "TCS.NS",
        "LT.NS", "SBIN.NS", "AXISBANK.NS", "KOTAKBANK.NS", "BHARTIARTL.NS",
        "ITC.NS", "HINDUNILVR.NS", "BAJFINANCE.NS", "WIPRO.NS", "ASIANPAINT.NS",
        "HCLTECH.NS", "ADANIENT.NS", "ADANIPORTS.NS", "NESTLEIND.NS", "SUNPHARMA.NS",
        "MARUTI.NS", "POWERGRID.NS", "ULTRACEMCO.NS", "TITAN.NS", "TATASTEEL.NS",
        "TECHM.NS", "HDFCLIFE.NS", "NTPC.NS", "JSWSTEEL.NS", "BAJAJFINSV.NS",
        "COALINDIA.NS", "BPCL.NS", "ONGC.NS", "SBILIFE.NS", "CIPLA.NS",
        "DRREDDY.NS", "DIVISLAB.NS", "EICHERMOT.NS", "GRASIM.NS", "HEROMOTOCO.NS",
        "HINDALCO.NS", "ICICIPRULI.NS", "INDUSINDBK.NS", "M&M.NS", "BRITANNIA.NS",
        "BAJAJ-AUTO.NS", "SHREECEM.NS", "TATACONSUM.NS", "UPL.NS", "BPCL.NS"
    ]
